name: Hello World Workflow

on: 
  push:
    branches: [master]
jobs:
  test-shell-script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step_1:Clone+Checkout the repo to runner
        uses: actions/checkout@v4

      - name: Step_2:Run shell script
        run: |
          echo "---------------------------------- start"
          echo "Hello!"
          echo "---------------------------------- dir"
          dir
          echo "---------------------------------- content of 1.txt"
          cat 1.txt 
          echo "---------------------------------- end"
          
