name: Hello World Workflow

on: 
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Name:Checkout code
        uses: actions/checkout@v4

      - name: Name:Say Hello
        run: cat 1.txt #echo "Hello, GitHub Actions!"
